import { useEffect, useMemo, useState } from "react";
import { ADMIN_CHECKLIST_GUARD_TEXTS, adminChecklistPrintHeaderLines, sortChecklistItems, toChecklistCsv } from "./adminChecklistCsv.mjs";
import { AdminChecklistDetail, AdminChecklistTable } from "./AdminChecklistTable.jsx";

// T-A2: the admin-check workflow screen. It renders the generated checklist as
// it is: no judgement, no rounding, no filling of UNKNOWN, no re-ranking.

const OBJECT_TYPES = ["edge", "facility", "plaza"];
const STATUSES = ["CONFIRMED", "UNKNOWN", "NOT_CONNECTED", "PERMISSION_REQUIRED"];
const METHODS = ["FIELD_MEASUREMENT", "OFFICIAL_QUERY", "DOCUMENT_REVIEW", "NOT_APPLICABLE"];

/** Load the generated checklist. Same timeout / notice convention as loadCatalog. */
export async function loadAdminChecklist(fetchImpl, path, expectedCityId, timeoutMs = 5000) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetchImpl(path, { signal: controller.signal });
    if (!response.ok) throw new Error(`admin checklist HTTP ${response.status}`);
    const text = await response.text();
    if (new TextEncoder().encode(text).byteLength > 16_000_000) throw new Error("admin checklist payload exceeds the static viewer byte limit");
    const checklist = JSON.parse(text);
    if (checklist?.city_id !== expectedCityId) throw new Error("admin checklist city binding mismatch");
    if (!Array.isArray(checklist.items)) throw new Error("admin checklist has no items");
    if (checklist.items.some((item) => item.internal_use_only === true)) throw new Error("admin checklist contains internal_use_only rows");
    return checklist;
  } finally {
    clearTimeout(timer);
  }
}

function toggle(values, value) {
  return values.includes(value) ? values.filter((entry) => entry !== value) : [...values, value];
}

function FilterGroup({ legend, options, selected, onChange }) {
  return (
    <fieldset className="admin-filter">
      <legend>{legend}</legend>
      {options.map((option) => (
        <label key={option}>
          <input type="checkbox" checked={selected.includes(option)} onChange={() => onChange(toggle(selected, option))} />
          <span>{option}</span>
        </label>
      ))}
    </fieldset>
  );
}

export function AdminChecklistPanel({ checklist, notice }) {
  const [objectTypes, setObjectTypes] = useState([]);
  const [statuses, setStatuses] = useState([]);
  const [methods, setMethods] = useState([]);
  const [selectedItemId, setSelectedItemId] = useState(null);
  useEffect(() => { setObjectTypes([]); setStatuses([]); setMethods([]); setSelectedItemId(null); }, [checklist?.city_id]);

  const visible = useMemo(() => {
    if (!checklist) return [];
    return sortChecklistItems(checklist.items.filter((item) =>
      (objectTypes.length === 0 || objectTypes.includes(item.object_type))
      && (statuses.length === 0 || statuses.includes(item.status))
      && (methods.length === 0 || methods.includes(item.verification_method))));
  }, [checklist, objectTypes, statuses, methods]);

  if (!checklist) {
    return (
      <section className="admin-checklist" aria-labelledby="admin-checklist-title">
        <div className="section-heading"><p className="eyebrow">ADMIN CHECK WORKFLOW</p><h2 id="admin-checklist-title">行政確認ワークフロー</h2></div>
        <p>{notice ?? "確認票を読み込めませんでした。"}</p>
      </section>
    );
  }

  const headerLines = adminChecklistPrintHeaderLines(checklist);
  const selected = checklist.items.find((item) => item.item_id === selectedItemId) ?? null;
  const internalRows = checklist.items.filter((item) => item.internal_use_only === true).length;

  function saveCsv() {
    // The exported bytes are the generated bytes: the whole item list through the
    // same serializer the build script uses, not the filtered view.
    const url = URL.createObjectURL(new Blob([toChecklistCsv(checklist.items)], { type: "text/csv;charset=utf-8" }));
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `ADMIN_CHECKLIST_${checklist.city_id}.csv`;
    document.body.append(anchor);
    anchor.click();
    anchor.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1_000);
  }

  return (
    <section className="admin-checklist" aria-labelledby="admin-checklist-title">
      <div className="section-heading"><p className="eyebrow">ADMIN CHECK WORKFLOW</p><h2 id="admin-checklist-title">行政確認ワークフロー</h2></div>
      <div className="admin-print-header">
        {headerLines.map((line) => <p key={line}>{line}</p>)}
      </div>
      <p className="admin-internal-note">
        {checklist.city_id === "fujisawa_enoshima"
          ? `既定の公開ビルドです。internal_use_only の行は含まれていません（この画面の内部利用行 ${internalRows} 件）。藤沢の施設行は LICENSE_REVIEW_REQUIRED のため既定ビルドから除外されます。行データの状態: ${checklist.fujisawa_facility_row_source_status ?? "null"}。`
          : `既定の公開ビルドです。internal_use_only の行は含まれていません（この画面の内部利用行 ${internalRows} 件）。`}
      </p>
      <div className="admin-filters">
        <FilterGroup legend="object_type" options={OBJECT_TYPES} selected={objectTypes} onChange={setObjectTypes} />
        <FilterGroup legend="status" options={STATUSES} selected={statuses} onChange={setStatuses} />
        <FilterGroup legend="verification_method" options={METHODS} selected={methods} onChange={setMethods} />
      </div>
      <p className="admin-counts">絞り込み後 / 全体: <b>{visible.length}</b> / {checklist.counts.items}</p>
      <div className="admin-actions">
        <button type="button" onClick={() => window.print()}>印刷</button>
        <button type="button" onClick={saveCsv}>CSVを保存（全{checklist.counts.items}行）</button>
        <a href={`./data/admin/${checklist.city_id}.checklist.json`} download={`${checklist.city_id}.checklist.json`}>JSON（生成済みファイル）</a>
      </div>
      <AdminChecklistTable items={visible} selectedItemId={selectedItemId} onSelect={setSelectedItemId} />
      <div className="admin-detail">
        <h3>行詳細</h3>
        <AdminChecklistDetail item={selected} />
      </div>
    </section>
  );
}
