// Pure module: constants + serializers for the admin-check checklist (T-A).
// No I/O, no side effects. Imported by viewer/scripts/build-map-artifacts.mjs,
// viewer/src/AdminChecklist*.jsx and tests/ui/admin_checklist.test.mjs so the
// generated bytes and the in-browser export come from one implementation.
//
// This module produces no judgement. It never derives passability, safety or
// accessibility, never fills UNKNOWN, and never converts a status word into a
// four-state verdict.

export const ADMIN_CHECKLIST_SCHEMA = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://ablepath.local/schemas/admin_checklist_item_v1.json",
    "title": "AblePath admin checklist item v1",
    "description": "行政確認ワークフローの1行。既存receiptの機械変換のみで生成される。通行可否・安全性・アクセシビリティの判定を含まない。UNKNOWNは通行不可でも可でもない。露出は被害ではない。",
    "schema_version": "1.0.0",
    "draft_status": "CONTRACT_EMBEDDED_FROM_ADMIN_CHECKLIST_SCHEMA_DRAFT_V1",
    "safety_claim": false,
    "accessibility_claim": false,
    "admin_validated": false,
    "type": "object",
    "additionalProperties": false,
    "required": [
      "item_id",
      "city_id",
      "subarea_id",
      "object_type",
      "object_id",
      "attribute",
      "status",
      "source_id",
      "source_revision",
      "source_sha256",
      "unknown_reason",
      "verification_method",
      "verification_target",
      "priority_rank",
      "priority_rule",
      "exposure_flags",
      "human_fields",
      "export_ready",
      "internal_use_only"
    ],
    "properties": {
      "item_id": {
        "type": "string",
        "description": "\"<city_id>:<object_type>:<object_id>:<attribute>\"。全city横断で一意。",
        "pattern": "^[a-z_]+:(edge|facility|plaza):.+:[A-Za-z0-9_.]+$"
      },
      "city_id": {
        "type": "string",
        "enum": [
          "kyoto_kiyomizu",
          "kyoto_arashiyama",
          "fujisawa_enoshima"
        ]
      },
      "subarea_id": {
        "type": "string",
        "description": "receiptがsubareaを明示している場合のみ実値。edgeにはsubareaを割り当てるreceiptが存在しないため SUBAREA_NOT_ASSIGNED_IN_RECEIPTS。幾何からの推定で埋めない。 ／ 注: kiyomizu / gion / kiyomizu_gion_connector は現時点の receipt からは生成されない値（幾何推定で埋めないこと）",
        "enum": [
          "kiyomizu",
          "gion",
          "kiyomizu_gion_connector",
          "kiyomizu_gion",
          "arashiyama",
          "enoshima_katase",
          "SUBAREA_NOT_ASSIGNED_IN_RECEIPTS"
        ]
      },
      "object_type": {
        "type": "string",
        "enum": [
          "edge",
          "facility",
          "plaza"
        ]
      },
      "object_id": {
        "type": "string",
        "description": "edge_id / facility_record_id / \"<city_id>:<category>\"。",
        "minLength": 1
      },
      "attribute": {
        "type": "string",
        "description": "edgeはcontract_v2の8フィールド、施設は facility.<field>、plazaは plaza.category_row_connection。",
        "enum": [
          "clear_width_m",
          "height_m",
          "setback_m",
          "damage_state",
          "debris_present",
          "official_closure",
          "hazard_data_status",
          "side_coverage",
          "facility.coordinate",
          "facility.operation_status",
          "facility.entrance_status",
          "facility.accessibility_status",
          "facility.safety_status",
          "facility.geometry",
          "facility.accessible_entrance",
          "facility.wheelchair_accessible",
          "facility.step_free",
          "facility.opening_status",
          "facility.disaster_availability",
          "plaza.category_row_connection"
        ]
      },
      "status": {
        "type": "string",
        "description": "4値のみ。PASS/CONDITIONAL/FAIL/OPENへ変換しない。",
        "enum": [
          "CONFIRMED",
          "UNKNOWN",
          "NOT_CONNECTED",
          "PERMISSION_REQUIRED"
        ]
      },
      "source_id": {
        "type": [
          "string",
          "null"
        ],
        "description": "status=CONFIRMEDのとき必須。それ以外はnull。"
      },
      "source_revision": {
        "type": [
          "string",
          "null"
        ],
        "description": "source_version_or_valid_as_of 等。CONFIRMED以外はnull。"
      },
      "source_sha256": {
        "type": [
          "string",
          "null"
        ],
        "description": "根拠artifactのLF正規化バイトのSHA-256（生成時に再計算。receiptからの転記ではない）。入力はLFであるため生バイトのSHA-256と一致する。",
        "pattern": "^[0-9a-f]{64}$"
      },
      "unknown_reason": {
        "type": [
          "string",
          "null"
        ],
        "description": "receipt内に実在する状態語の逐語コピー。新しい理由語を作らない。CONFIRMEDのときnull。"
      },
      "verification_method": {
        "type": "string",
        "enum": [
          "FIELD_MEASUREMENT",
          "OFFICIAL_QUERY",
          "DOCUMENT_REVIEW",
          "NOT_APPLICABLE"
        ]
      },
      "verification_target": {
        "type": "object",
        "description": "誰に聞くか／何を測るか。label・noteはreceiptの文字列をコピーし、要約や言い換えをしない。",
        "additionalProperties": false,
        "required": [
          "label",
          "receipt_path",
          "dataset_ids",
          "note"
        ],
        "properties": {
          "label": {
            "type": "string",
            "minLength": 1
          },
          "receipt_path": {
            "type": [
              "string",
              "null"
            ]
          },
          "dataset_ids": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "note": {
            "type": [
              "string",
              "null"
            ]
          }
        }
      },
      "priority_rank": {
        "type": "integer",
        "description": "並び順の機械規則。危険度・重要度・リスクではない。",
        "enum": [
          1,
          2,
          3
        ]
      },
      "priority_rule": {
        "type": "string",
        "enum": [
          "PILOT_EDGE",
          "CONNECTOR_SCOPED",
          "FACILITY_WITH_SOURCE_COORDINATES",
          "DEFAULT"
        ]
      },
      "exposure_flags": {
        "type": [
          "object",
          "null"
        ],
        "description": "edge行のみ。M7_PILOT_EXPOSURE_ONLY_JOIN_V1 の集計。facility/plazaではnull。",
        "additionalProperties": false,
        "required": [
          "records",
          "status",
          "reason",
          "a31b_overlap_counts",
          "landslide",
          "earthquake",
          "liquefaction",
          "tsunami",
          "note"
        ],
        "properties": {
          "status": { "enum": ["SOURCE_RECORDS", "PUBLIC_PAYLOAD_EXCLUDED"] },
          "reason": { "type": ["string", "null"] },
          "records": {
            "type": ["integer", "null"],
            "minimum": 0
          },
          "a31b_overlap_counts": {
            "type": ["object", "null"],
            "description": "a31b_flood_overlap の値別件数。キーはreceiptの値をそのまま使う。",
            "additionalProperties": {
              "type": "integer",
              "minimum": 0
            }
          },
          "landslide": {
            "type": "string"
          },
          "earthquake": {
            "type": "string"
          },
          "liquefaction": {
            "type": "string",
            "const": "NOT_CONNECTED"
          },
          "tsunami": {
            "type": "string",
            "const": "NOT_CONNECTED"
          },
          "note": {
            "type": "string",
            "const": "露出は被害ではない。damage_state・debris_present・official_closure・通行可否を導出しない。"
          }
        },
        "allOf": [{
          "if": { "properties": { "status": { "const": "PUBLIC_PAYLOAD_EXCLUDED" } }, "required": ["status"] },
          "then": { "properties": { "records": { "type": "null" }, "a31b_overlap_counts": { "type": "null" }, "reason": { "type": "string", "minLength": 1 } } },
          "else": { "properties": { "records": { "type": "integer" }, "a31b_overlap_counts": { "type": "object" }, "reason": { "type": "null" } } }
        }]
      },
      "human_fields": {
        "type": "object",
        "description": "人が印刷物または内部運用で埋める欄。生成物では常に空（null）。",
        "additionalProperties": false,
        "required": [
          "assignee",
          "due",
          "result",
          "note"
        ],
        "properties": {
          "assignee": {
            "type": "null"
          },
          "due": {
            "type": "null"
          },
          "result": {
            "type": "null"
          },
          "note": {
            "type": "null"
          }
        }
      },
      "export_ready": {
        "type": "boolean",
        "description": "status・verification_method・verification_target・priority_rankがすべて規則から決まった行のみtrue。falseの行も落とさず、原因をunknown_reasonに残す。"
      },
      "internal_use_only": {
        "type": "boolean",
        "description": "trueの行は公開ビルドに含めない（藤沢施設行）。既定ビルドにtrueが1件でもあればfail-closedで停止。"
      },
      "_example": {
        "type": "string",
        "description": "Present only on synthetic examples (EXAMPLE_SYNTHETIC_NOT_A_RECEIPT_VALUE); never in generated data"
      }
    },
    "allOf": [
      {
        "if": {
          "properties": {
            "status": {
              "const": "CONFIRMED"
            }
          },
          "required": [
            "status"
          ]
        },
        "then": {
          "properties": {
            "source_id": {
              "type": "string"
            },
            "source_sha256": {
              "type": "string"
            },
            "unknown_reason": {
              "type": "null"
            },
            "verification_method": {
              "const": "NOT_APPLICABLE"
            }
          }
        },
        "else": {
          "properties": {
            "source_id": {
              "type": "null"
            },
            "source_revision": {
              "type": "null"
            },
            "source_sha256": {
              "type": "null"
            },
            "unknown_reason": {
              "type": "string"
            }
          }
        }
      },
      {
        "if": {
          "properties": {
            "object_type": {
              "const": "edge"
            }
          },
          "required": [
            "object_type"
          ]
        },
        "then": {
          "properties": {
            "exposure_flags": {
              "type": "object"
            }
          }
        },
        "else": {
          "properties": {
            "exposure_flags": {
              "type": "null"
            }
          }
        }
      }
    ]
  };

export const EXPOSURE_NOTE = "露出は被害ではない。damage_state・debris_present・official_closure・通行可否を導出しない。";

/** Fixed guard/disclaimer sentences. Verbatim only; the scanner allowlist is built from these. */
export const ADMIN_CHECKLIST_GUARD_TEXTS = Object.freeze([
  "この表は行政による検証結果ではありません。通行可否・安全性・アクセシビリティの判定を含みません。",
  "露出は被害ではない。",
  "UNKNOWNは通行不可でも可でもない。",
  "priority_rank は並び順の機械規則であり、危険度・重要度ではありません。",
  EXPOSURE_NOTE,
]);

function schemaProseStrings(node, out = []) {
  if (Array.isArray(node)) { for (const value of node) schemaProseStrings(value, out); return out; }
  if (node && typeof node === "object") {
    for (const [key, value] of Object.entries(node)) {
      if ((key === "title" || key === "description") && typeof value === "string") out.push(value);
      else schemaProseStrings(value, out);
    }
  }
  return out;
}

/**
 * Verbatim strings a forbidden-expression scan may subtract before asserting zero hits.
 * Only exact fixed sentences belong here: no wildcards, no regular expressions.
 */
export const ADMIN_CHECKLIST_ALLOWED_TEXTS = Object.freeze([
  ...ADMIN_CHECKLIST_GUARD_TEXTS,
  ...schemaProseStrings(ADMIN_CHECKLIST_SCHEMA),
]);

/** Words that must never appear outside the allowlisted fixed sentences. */
export const ADMIN_CHECKLIST_FORBIDDEN_WORDS = Object.freeze([
  "安全な避難ルート", "安全", "危険", "通行可", "通行不可", "再現", "救える",
]);

export function scanForbiddenExpressions(text, allowed = ADMIN_CHECKLIST_ALLOWED_TEXTS) {
  let residue = String(text);
  for (const sentence of [...allowed].sort((left, right) => right.length - left.length)) {
    residue = residue.split(sentence).join(" ");
  }
  return ADMIN_CHECKLIST_FORBIDDEN_WORDS.filter((word) => residue.includes(word));
}

/** Validate the public exposure boundary; never fill absent evidence with zero. */
export function validateExposureFlags(value) {
  if (value?.status === "PUBLIC_PAYLOAD_EXCLUDED") {
    if (value.records !== null || value.a31b_overlap_counts !== null || typeof value.reason !== "string" || !value.reason.trim()) throw new Error("excluded exposure must remain null with a reason");
  } else if (value?.status !== "SOURCE_RECORDS" || !Number.isInteger(value.records) || value.records < 0 || !value.a31b_overlap_counts || value.reason !== null) {
    throw new Error("invalid exposure source records");
  }
}

/** Header lines printed above every checklist print view. Data comes from the checklist header. */
export function adminChecklistPrintHeaderLines(checklist) {
  const sources = Object.entries(checklist?.generated_from ?? {}).map(([path, sha256]) => `${path} ${sha256}`);
  return [
    `AblePath 行政確認ワークフロー（${checklist?.city_id ?? "null"} / generated_at ${checklist?.generated_at ?? "null"}）`,
    ...ADMIN_CHECKLIST_GUARD_TEXTS.slice(0, 4),
    `出典: ${sources.join(" / ")}`,
    `M6: ${checklist?.m6_status ?? "null"} / M7: ${checklist?.m7_status ?? "null"}`,
  ];
}

export const ADMIN_CHECKLIST_CSV_COLUMNS = Object.freeze([
  "item_id", "city_id", "subarea_id", "object_type", "object_id", "attribute", "status",
  "source_id", "source_revision", "source_sha256", "unknown_reason", "verification_method",
  "verification_target.label", "verification_target.receipt_path", "verification_target.dataset_ids",
  "verification_target.note", "priority_rank", "priority_rule", "exposure_flags",
  "human_fields.assignee", "human_fields.due", "human_fields.result", "human_fields.note",
  "export_ready", "internal_use_only",
]);

function cell(value) {
  if (value === null || value === undefined) return "";
  const text = typeof value === "string" ? value : JSON.stringify(value);
  return /[",\n\r]/.test(text) ? `"${text.split('"').join('""')}"` : text;
}

function column(item, name) {
  if (name === "exposure_flags") return item.exposure_flags === null ? "" : JSON.stringify(item.exposure_flags);
  if (name === "verification_target.dataset_ids") return JSON.stringify(item.verification_target?.dataset_ids ?? []);
  const [head, tail] = name.split(".");
  const value = tail === undefined ? item[head] : item[head]?.[tail];
  return typeof value === "boolean" || typeof value === "number" ? String(value) : value ?? null;
}

/** RFC4180 serializer. LF line endings, no BOM. Pure. */
export function toChecklistCsv(items) {
  const rows = [ADMIN_CHECKLIST_CSV_COLUMNS.join(",")];
  for (const item of items) rows.push(ADMIN_CHECKLIST_CSV_COLUMNS.map((name) => cell(column(item, name))).join(","));
  return `${rows.join("\n")}\n`;
}

/**
 * Code-point comparison. localeCompare is not used anywhere in the generated
 * ordering: its result depends on the host ICU data, which would make the
 * generated bytes machine-dependent.
 */
export function compareCodePoints(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

/** Default machine ordering: priority_rank, then object_type, object_id, attribute (all by code point, stable). */
export function sortChecklistItems(items) {
  return [...items].sort((left, right) =>
    left.priority_rank - right.priority_rank
    || compareCodePoints(left.object_type, right.object_type)
    || compareCodePoints(left.object_id, right.object_id)
    || compareCodePoints(left.attribute, right.attribute)
    || compareCodePoints(left.item_id, right.item_id));
}
